<a href="https://colab.research.google.com/github/El-Nico/tensorflow-notes/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# fundamental concepts of tensors using tensor flow

* introduction to tensors
* getting information from tensors
* manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up regular python functions)
* Using GPUS with TensorFlow (or TPUs)
* Excersises to try myself

# Introduction to Tensors

In [3]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
# create a tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor 
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# create a matrix (has more than 1 deminsio)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# check the dimension of the matrix
matrix.ndim

2

In [ ]:
# some random tensors
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [ ]:
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]])
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

# manipulating tensors

* basic operations
* +. -, *./


In [ ]:
tensor = tf.constant ([[10,7],
                       [3,4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor_a = tf.constant([[1,2],
                        [3,4],
                        [5,6]])


# New Tensors again
# Create random tensors


In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # create tensor from a normal distribution
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [12]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A, shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array

numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [ ]:
# create a rank 4 tensor
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# get and print various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array



Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [ ]:
# indexing tensors like python lists
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
X= tf.constant([[1, 2],
                [3, 4],
                [5, 6]])

Y= tf.constant([
               [7, 8],
               [9, 10],
               [11, 12]
                ]   
               )
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# reshape the tensor so it is multipliable
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:

tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([33, 21,  9, 23, 73,  5, 22, 31, 79, 95, 52,  1, 80, 66, 46, 40, 81,
        4, 54, 24, 25,  1, 67, 95, 92, 68, 18, 37, 17,  4, 61,  1, 22, 50,
       49, 89, 23, 68, 14, 40, 48, 27, 80, 38, 53, 11,  8, 60, 25, 70])>

In [ ]:
# find the minimum value
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
tf.reduce_sum(E)


<tf.Tensor: shape=(), dtype=int64, numpy=2100>

In [5]:
print(tf.config.list_physical_devices('GPU'))
!nvidia-smi


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Mon Sep 27 08:57:53 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8    27W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                     

# Excercises



1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [9]:
# a scalar
SCALAR=tf.constant(1)
# a vector
VECTOR=tf.constant([1,2,3,4])
# a matrix
MATRIX=tf.constant([
             [1,2],
             [3,4]])
# a tensor
TENSOR=tf.ones(shape=(3,4))

SCALAR, VECTOR, MATRIX, TENSOR

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>)

2. Find the shape, rank and size of the tensors you created in 1.

In [11]:
SCALAR.shape,SCALAR.ndim, tf.size(SCALAR)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

create two tensors containing random values between 0 and 1 with shape [5,300].

In [23]:
tensor_1= tf.constant(np.arange(0,1), shape=(5, 300))
tensor_2=tf.constant(np.arange(0,1), shape=(5, 300))
tensor_3=tf.random.Generator.from_seed(42)
tensor_3=tensor_3.normal(shape=(5,300))

tensor_1, tensor_2, tensor_3

(<tf.Tensor: shape=(5, 300), dtype=int64, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])>,
 <tf.Tensor: shape=(5, 300), dtype=int64, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.0718341 ,
         -1.0722276 , -0.00586287],
        [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
          1.155565  , -0.10707551],
        [-1.5306779 , -0.8620293 , -0.16359143, ...,  0.34288087,
          1.2167931 , -1.24293   ],
        [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
         -0.73970354,  0.0177109 ],
        [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
          0.5656089 ,  0.18439198]], dtyp

Multiply the two tensors created in 3 using matrix multiplication

In [21]:
tf.matmul(tensor_1, tf.transpose(tensor_2))

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

multiply the two tensors created in 3 using dot product

In [27]:
tf.tensordot(tensor_1, tf.reshape(tensor_2, shape=(300,5)), axes=1)

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

6. create a temsor with random values between 0 1nd 1 with shape [224, 224, 3].

In [29]:
tensor_4 = tf.random.Generator.from_seed(42)
tensor_4 = tensor_4.normal(shape=(224,224, 3))
tensor_4

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535806 ],
        ...,
        [ 0.07099114, -0.5095768 ,  0.3482001 ],
        [ 0.15985982, -1.9042184 ,  0.9690504 ],
        [ 0.16251186, -0.07330751, -0.36059096]],

       [[ 0.18739441, -0.73353654,  1.2104433 ],
        [ 1.5603006 , -0.48115277,  0.6335167 ],
        [-0.5612103 ,  0.06994031,  1.6807096 ],
        ...,
        [-1.9460295 , -0.7977275 ,  0.03092833],
        [ 0.8297488 ,  0.12179119,  1.0506108 ],
        [-1.3097638 ,  0.92536974, -1.1787732 ]],

       [[-0.21711825, -0.73974085, -1.3077081 ],
        [-0.7502274 , -0.37715855, -0.30130875],
        [ 1.0943383 ,  0.255803  ,  0.8011465 ],
        ...,
        [-0.32833767, -0.7794747 ,  0.20049337],
        [-0.09002841,  0.07243238, -0.81940895],
        [ 0.3171264 , -1.6143695 , -1.6824652 ]],

       ...,

     

7. Find the min and max values of the tensor created in 6