<a href="https://colab.research.google.com/github/El-Nico/tensorflow-notes/blob/main/NumPy_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


#**DataTypes & Attributes**

In [4]:
# NumPy's main datatyp is ndarray and forms the basis of all datatypes
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [12]:
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17, 18]]])

In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a1.shape

(3,)

In [16]:
a2.shape

(2, 3)

In [17]:
a3.shape

(2, 3, 3)

In [19]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [20]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [21]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [22]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [26]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

#**2. Creating Arrays**

In [27]:
sample_array= np.array([1,2,3])
sample_array

array([1, 2, 3])

In [28]:
sample_array.dtype

dtype('int64')

In [29]:
ones = np.ones((2,3))

In [30]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
ones.dtype

dtype('float64')

In [32]:
type(ones)

numpy.ndarray

In [33]:
zeros = np.zeros((2,3))

In [34]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [38]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[6, 5, 8, 6, 0],
       [8, 3, 2, 0, 7],
       [4, 0, 6, 7, 9]])

In [39]:
random_array.size

15

In [40]:
random_array.shape

(3, 5)

In [42]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.36407157, 0.90736796, 0.07060026],
       [0.97558869, 0.54286009, 0.13479161],
       [0.64095247, 0.8224809 , 0.71300701],
       [0.56329335, 0.15953846, 0.79139635],
       [0.27994164, 0.90200679, 0.6253837 ]])

In [43]:
random_array_2.shape

(5, 3)

In [48]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.86326942, 0.38258418, 0.57999818],
       [0.5927722 , 0.37828752, 0.9615567 ],
       [0.59381134, 0.42319794, 0.23733791],
       [0.66736472, 0.17062266, 0.9595879 ],
       [0.81328176, 0.62315053, 0.52925353]])

In [56]:
# Pseudo-random numbers
np.random.seed(seed=0)

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [59]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [61]:
#different
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [60]:
random_array_4.shape

(5, 3)

#**3. Viewing Arrays and Matrices**

In [62]:
#find all the unique numbers of array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
#sec3
a1

array([1, 2, 3])

In [64]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [65]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [68]:
#el zero
a1[0]

1

In [72]:
a2.shape

(2, 3)

In [69]:
a2[0]

array([1. , 2. , 3.3])

In [71]:
a3.shape

(2, 3, 3)

In [73]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [79]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 1, 1, 8, 4],
         [2, 1, 7, 0, 8],
         [8, 1, 2, 3, 0],
         [1, 1, 5, 5, 6]],

        [[0, 9, 3, 2, 4],
         [2, 8, 4, 9, 0],
         [0, 2, 6, 3, 9],
         [5, 4, 6, 9, 9]],

        [[9, 4, 8, 2, 4],
         [6, 5, 3, 5, 2],
         [6, 4, 3, 2, 5],
         [9, 7, 5, 8, 5]]],


       [[[2, 0, 9, 3, 2],
         [2, 4, 3, 4, 8],
         [7, 0, 2, 7, 8],
         [8, 4, 0, 4, 1]],

        [[7, 4, 9, 0, 1],
         [0, 6, 2, 0, 2],
         [4, 4, 1, 0, 0],
         [2, 3, 7, 6, 9]],

        [[3, 5, 6, 8, 6],
         [7, 3, 8, 5, 6],
         [4, 2, 7, 9, 6],
         [8, 6, 1, 0, 7]]]])

In [82]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [83]:
#get the first 4 numbers of the inner most arrays
a4[:,:,:,:4]

array([[[[3, 1, 1, 8],
         [2, 1, 7, 0],
         [8, 1, 2, 3],
         [1, 1, 5, 5]],

        [[0, 9, 3, 2],
         [2, 8, 4, 9],
         [0, 2, 6, 3],
         [5, 4, 6, 9]],

        [[9, 4, 8, 2],
         [6, 5, 3, 5],
         [6, 4, 3, 2],
         [9, 7, 5, 8]]],


       [[[2, 0, 9, 3],
         [2, 4, 3, 4],
         [7, 0, 2, 7],
         [8, 4, 0, 4]],

        [[7, 4, 9, 0],
         [0, 6, 2, 0],
         [4, 4, 1, 0],
         [2, 3, 7, 6]],

        [[3, 5, 6, 8],
         [7, 3, 8, 5],
         [4, 2, 7, 9],
         [8, 6, 1, 0]]]])