<a href="https://colab.research.google.com/github/El-Nico/tensorflow-notes/blob/main/tensor_flow_fundamentals_excercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercises

    Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
    Find the shape, rank and size of the tensors you created in 1.
    Create two tensors containing random values between 0 and 1 with shape [5, 300].
    Multiply the two tensors you created in 3 using matrix multiplication.
    Multiply the two tensors you created in 3 using dot product.
    Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
    Find the min and max values of the tensor you created in 6.
    Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
    Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
    One-hot encode the tensor you created in 9.


Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [23]:
import tensorflow as tf

In [24]:
# scalar: a single number
scalar=tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [25]:
# vector: a number with direction (e.g wind speed with direction)
vector = tf.constant([1, -1])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, -1], dtype=int32)>

In [26]:
# matrix: a 2-dimenstional array of numbers
matrix = tf.constant([[1,-1],[2,-2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1, -1],
       [ 2, -2]], dtype=int32)>

In [27]:
# tensor: an n-dimesnional array of numbers
tensor = tf.constant([[[1,-1],[2,-2]]])
type(tensor)

tensorflow.python.framework.ops.EagerTensor

    Find the shape, rank and size of the tensors you created in 1.

In [28]:
def shapeRankSize(tensor):
  dict={
      "shape":tensor.shape,
      "rank":tensor.ndim,
      "size":tf.size(tensor)
  }
  return dict

In [29]:
shapeRankSize(scalar)

{'rank': 0,
 'shape': TensorShape([]),
 'size': <tf.Tensor: shape=(), dtype=int32, numpy=1>}

In [30]:
shapeRankSize(vector)

{'rank': 1,
 'shape': TensorShape([2]),
 'size': <tf.Tensor: shape=(), dtype=int32, numpy=2>}

In [31]:
shapeRankSize(matrix)

{'rank': 2,
 'shape': TensorShape([2, 2]),
 'size': <tf.Tensor: shape=(), dtype=int32, numpy=4>}

In [32]:
shapeRankSize(tensor)

{'rank': 3,
 'shape': TensorShape([1, 2, 2]),
 'size': <tf.Tensor: shape=(), dtype=int32, numpy=4>}

Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [37]:
tensor_a=tf.random.Generator.from_non_deterministic_state()
tensor_a=tensor_a.normal(shape=(5,300))
tensor_a

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[ 0.268175  , -1.3858562 , -1.4589622 , ...,  0.31372383,
         0.24789768,  1.0707144 ],
       [-0.37637767,  2.2559125 ,  1.0110713 , ..., -1.4557099 ,
         1.4666694 , -0.5513001 ],
       [-0.550927  ,  1.191241  ,  0.15870339, ...,  0.00495694,
         0.79631686, -0.23236117],
       [-0.4862674 , -1.3735552 ,  0.07065798, ...,  0.8274821 ,
        -0.39212382,  0.92246735],
       [ 1.652738  , -0.05592356, -1.6939905 , ..., -0.9000042 ,
         1.0239352 , -1.3474562 ]], dtype=float32)>

In [38]:
tensor_b=tf.random.Generator.from_non_deterministic_state()
tensor_b=tensor_b.normal(shape=(5,300))
tensor_b

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[ 0.5282492 ,  0.5624945 ,  0.7625461 , ...,  1.0876051 ,
        -0.09800553, -1.8361394 ],
       [-1.6982691 , -1.3597176 ,  1.1529174 , ...,  0.6036257 ,
        -1.0372176 , -0.08630739],
       [ 0.45138454,  1.5454129 ,  0.92797554, ..., -0.3166346 ,
         1.3658845 , -0.5803283 ],
       [ 0.4160652 , -2.081101  , -0.72141296, ...,  0.82562363,
        -1.5295949 , -0.26127797],
       [-0.8730775 ,  1.8739595 ,  0.11632651, ...,  0.2593781 ,
        -0.8669354 , -1.0283298 ]], dtype=float32)>

    Multiply the two tensors you created in 3 using matrix multiplication.
    Multiply the two tensors you created in 3 using dot product.


In [40]:
tf.matmul(tf.reshape(tensor_a, shape=(300, 5)), tensor_b)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[ 1.3448797 ,  1.8673705 , -2.1035452 , ..., -0.76077694,
         0.61641556,  0.5468237 ],
       [-1.0730104 , -1.0424997 , -0.55313367, ...,  1.8835164 ,
        -3.0970852 , -1.5124043 ],
       [ 0.40168148,  7.033834  ,  1.9412943 , ..., -1.1149955 ,
         3.5443892 , -1.8953485 ],
       ...,
       [-2.4670494 ,  1.9887166 ,  0.7800135 , ...,  1.2224942 ,
        -2.4285088 , -2.050316  ],
       [-0.5948869 , -2.0394688 ,  1.2061028 , ...,  0.3893663 ,
        -0.01813916,  0.22261982],
       [-1.0205396 , -7.93234   , -1.1145314 , ...,  0.55769634,
        -2.647763  ,  3.0046613 ]], dtype=float32)>

In [44]:
#dot product
tf.tensordot(tf.transpose(tensor_a), tensor_b, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[-1.1131134 ,  3.9203403 , -0.19762649, ...,  0.26613   ,
        -1.0774246 , -1.7127129 ],
       [-4.5481787 ,  0.7477273 ,  3.633939  , ..., -1.6712706 ,
         1.572512  ,  2.0749998 ],
       [-0.9077471 , -5.2716837 , -0.04760094, ..., -1.4077642 ,
         0.6715581 ,  4.2230144 ],
       ...,
       [ 3.770209  , -1.2451624 , -2.136135  , ..., -0.08931844,
         1.000445  ,  0.2560195 ],
       [-3.0575266 ,  2.1106856 ,  3.0209386 , ...,  0.8446324 ,
        -0.7457689 , -1.9943743 ],
       [ 2.957216  , -3.4520366 , -0.8569847 , ...,  1.3174193 ,
        -0.09334016, -0.6389448 ]], dtype=float32)>

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].


In [49]:
rand_tensor=tf.random.uniform(shape=(224,224,3), minval=0, maxval=1)
rand_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.31765485, 0.592263  , 0.8793553 ],
        [0.76483226, 0.5455266 , 0.874552  ],
        [0.9883357 , 0.00122428, 0.10346496],
        ...,
        [0.54881084, 0.6926576 , 0.985698  ],
        [0.92919827, 0.16094506, 0.91804504],
        [0.44222915, 0.3657663 , 0.91509616]],

       [[0.526034  , 0.16607761, 0.02441108],
        [0.17276776, 0.82773244, 0.5285127 ],
        [0.3955227 , 0.6719173 , 0.89599156],
        ...,
        [0.38076782, 0.4107288 , 0.8994967 ],
        [0.57339215, 0.10584283, 0.66929233],
        [0.15140653, 0.46167958, 0.61496496]],

       [[0.8281493 , 0.6082463 , 0.41602647],
        [0.5742111 , 0.12155592, 0.18246377],
        [0.76691234, 0.91494405, 0.8686224 ],
        ...,
        [0.46839213, 0.6744658 , 0.03136826],
        [0.644137  , 0.88594127, 0.34500968],
        [0.80271757, 0.0691371 , 0.03424907]],

       ...,

       [[0.10885823, 0.43914568, 0.76810384],
        [0.78

Find the min and max values of the tensor you created in 6.

In [50]:
#min
tf.reduce_min(rand_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=3.33786e-06>

In [51]:
#max
tf.reduce_max(rand_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999654>

Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [52]:
rand_tensor_2=tf.random.uniform(shape=(1,224,224,3), minval=0, maxval=1)
rand_tensor_2

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.22728801, 0.8198496 , 0.75506485],
         [0.4126581 , 0.64660704, 0.69958997],
         [0.2093383 , 0.36787426, 0.93073213],
         ...,
         [0.31558335, 0.4384569 , 0.03134859],
         [0.14143014, 0.67960894, 0.9844302 ],
         [0.5778805 , 0.8336359 , 0.14731169]],

        [[0.98005056, 0.86298597, 0.89136016],
         [0.8317741 , 0.14459682, 0.3121971 ],
         [0.08505428, 0.5867263 , 0.02004611],
         ...,
         [0.38585806, 0.76760983, 0.03452075],
         [0.39992392, 0.46211863, 0.8342304 ],
         [0.92320883, 0.67471814, 0.8246417 ]],

        [[0.34677827, 0.192361  , 0.10799825],
         [0.595284  , 0.42747915, 0.15313554],
         [0.53637934, 0.08000302, 0.924742  ],
         ...,
         [0.32395446, 0.2330774 , 0.5454962 ],
         [0.42705   , 0.01555204, 0.42722905],
         [0.31724286, 0.8253027 , 0.2594391 ]],

        ...,

        [[0.1593039 , 0.2628752 , 

In [53]:
#remove extra dim
tf.squeeze(rand_tensor_2)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.22728801, 0.8198496 , 0.75506485],
        [0.4126581 , 0.64660704, 0.69958997],
        [0.2093383 , 0.36787426, 0.93073213],
        ...,
        [0.31558335, 0.4384569 , 0.03134859],
        [0.14143014, 0.67960894, 0.9844302 ],
        [0.5778805 , 0.8336359 , 0.14731169]],

       [[0.98005056, 0.86298597, 0.89136016],
        [0.8317741 , 0.14459682, 0.3121971 ],
        [0.08505428, 0.5867263 , 0.02004611],
        ...,
        [0.38585806, 0.76760983, 0.03452075],
        [0.39992392, 0.46211863, 0.8342304 ],
        [0.92320883, 0.67471814, 0.8246417 ]],

       [[0.34677827, 0.192361  , 0.10799825],
        [0.595284  , 0.42747915, 0.15313554],
        [0.53637934, 0.08000302, 0.924742  ],
        ...,
        [0.32395446, 0.2330774 , 0.5454962 ],
        [0.42705   , 0.01555204, 0.42722905],
        [0.31724286, 0.8253027 , 0.2594391 ]],

       ...,

       [[0.1593039 , 0.2628752 , 0.08793902],
        [0.66

Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [57]:
tensor_10=tf.random.uniform(shape=[10], minval=0, maxval=10, dtype=tf.dtypes.int32)
tensor_10

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 4, 2, 9, 6, 4, 0, 6, 2, 8], dtype=int32)>

In [58]:
#positional maximum and minimum is used to lineup label with pred prob
tf.argmax(tensor_10).numpy()

3

One-hot encode the tensor you created in 9.

In [61]:
tf.one_hot(tensor_10,depth=7)

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>